# Generated by Django 5.2.15 on 2026-06-29 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripción')),
                ('province', models.CharField(choices=[('Salta', 'Salta'), ('Jujuy', 'Jujuy'), ('Chaco', 'Chaco'), ('Formosa', 'Formosa')], max_length=50, verbose_name='provincia')),
                ('population', models.PositiveIntegerField(verbose_name='población')),
                ('email', models.EmailField(max_length=254, verbose_name='email de contacto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='communities/', verbose_name='imagen')),
                ('image_url', models.URLField(blank=True, verbose_name='URL de imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario responsable')),
            ],
            options={
                'verbose_name': 'comunidad',
                'verbose_name_plural': 'comunidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('category', models.CharField(choices=[('Alimentos', 'Alimentos'), ('Salud', 'Salud'), ('Educación', 'Educación'), ('Vivienda', 'Vivienda'), ('Otro', 'Otro')], max_length=50, verbose_name='categoría')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto objetivo')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='urgente')),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='activa', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='communities.community', verbose_name='comunidad')),
            ],
            options={
                'verbose_name': 'necesidad',
                'verbose_name_plural': 'necesidades',
                'ordering': ['-is_urgent', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('confirmation_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='código de confirmación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='donante')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='communities.need', verbose_name='necesidad')),
            ],
            options={
                'verbose_name': 'donación',
                'verbose_name_plural': 'donaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
